DROP TABLE IF EXISTS bookings, items, comments, users, requests CASCADE;
create TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create TABLE IF NOT EXISTS requests(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255) NOT NULL,
    created timestamp,
    requestor BIGINT REFERENCES users(user_id) ON DELETE CASCADE
);
create TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available Boolean,
    user_id BIGINT REFERENCES users (user_id) ON delete CASCADE NOT NULL,
    request BIGINT REFERENCES requests(request_id) ON DELETE SET NULL
);

create TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES items (item_id) ON delete CASCADE,
    booker_id BIGINT REFERENCES users (user_id) ON delete CASCADE,
    status VARCHAR,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL
);

create TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text VARCHAR,
    item_id BIGINT REFERENCES items (item_id) ON delete CASCADE,
    author_name varchar NOT NULL,
    created TIMESTAMP WITH TIME ZONE
);